import { Permission, PermissionAction, PermissionGroup } from '@app/common';

export const permissionsData: Partial<Permission>[] = [
  {
    id: 1,
    name: 'Create Products',
    action: PermissionAction.CREATE,
    group: PermissionGroup.PRODUCTS,
  },
  {
    id: 2,
    name: 'Update Products',
    action: PermissionAction.UPDATE,
    group: PermissionGroup.PRODUCTS,
  },
  {
    id: 3,
    name: 'View Products',
    action: PermissionAction.VIEW,
    group: PermissionGroup.PRODUCTS,
  },
  {
    id: 4,
    name: 'Delete Products',
    action: PermissionAction.DELETE,
    group: PermissionGroup.PRODUCTS,
  },
  {
    id: 5,
    name: 'Create Roles',
    action: PermissionAction.CREATE,
    group: PermissionGroup.ROLES,
  },
  {
    id: 6,
    name: 'Update Roles',
    action: PermissionAction.UPDATE,
    group: PermissionGroup.ROLES,
  },
  {
    id: 7,
    name: 'View Roles',
    action: PermissionAction.VIEW,
    group: PermissionGroup.ROLES,
  },
  {
    id: 8,
    name: 'Delete Roles',
    action: PermissionAction.DELETE,
    group: PermissionGroup.ROLES,
  },
  {
    id: 9,
    name: 'Create Admins',
    action: PermissionAction.CREATE,
    group: PermissionGroup.ADMINS,
  },
  {
    id: 10,
    name: 'Update Admins',
    action: PermissionAction.UPDATE,
    group: PermissionGroup.ADMINS,
  },
  {
    id: 11,
    name: 'View Admins',
    action: PermissionAction.VIEW,
    group: PermissionGroup.ADMINS,
  },
  {
    id: 12,
    name: 'Delete Admins',
    action: PermissionAction.DELETE,
    group: PermissionGroup.ADMINS,
  },
  {
    id: 13,
    name: 'Export Admins',
    action: PermissionAction.EXPORT,
    group: PermissionGroup.ADMINS,
  },
  {
    id: 14,
    name: 'Create Customers',
    action: PermissionAction.CREATE,
    group: PermissionGroup.CUSTOMERS,
  },
  {
    id: 15,
    name: 'Update Customers',
    action: PermissionAction.UPDATE,
    group: PermissionGroup.CUSTOMERS,
  },
  {
    id: 16,
    name: 'View Customers',
    action: PermissionAction.VIEW,
    group: PermissionGroup.CUSTOMERS,
  },
  {
    id: 17,
    name: 'Delete Customers',
    action: PermissionAction.DELETE,
    group: PermissionGroup.CUSTOMERS,
  },
  {
    id: 18,
    name: 'Export Customers',
    action: PermissionAction.EXPORT,
    group: PermissionGroup.CUSTOMERS,
  },
  {
    id: 19,
    name: 'Create Vendors',
    action: PermissionAction.CREATE,
    group: PermissionGroup.VENDORS,
  },
  {
    id: 20,
    name: 'Update Vendors',
    action: PermissionAction.UPDATE,
    group: PermissionGroup.VENDORS,
  },
  {
    id: 21,
    name: 'View Vendors',
    action: PermissionAction.VIEW,
    group: PermissionGroup.VENDORS,
  },
  {
    id: 22,
    name: 'Delete Vendors',
    action: PermissionAction.DELETE,
    group: PermissionGroup.VENDORS,
  },
  {
    id: 23,
    name: 'Export Vendors',
    action: PermissionAction.EXPORT,
    group: PermissionGroup.VENDORS,
  },
  {
    id: 24,
    name: 'Update Orders',
    action: PermissionAction.UPDATE,
    group: PermissionGroup.ORDERS,
  },
  {
    id: 25,
    name: 'View Orders',
    action: PermissionAction.VIEW,
    group: PermissionGroup.ORDERS,
  },
  {
    id: 26,
    name: 'Delete Orders',
    action: PermissionAction.DELETE,
    group: PermissionGroup.ORDERS,
  },
  {
    id: 27,
    name: 'Export Orders',
    action: PermissionAction.EXPORT,
    group: PermissionGroup.ORDERS,
  },
  {
    id: 28,
    name: 'Create Reasons',
    action: PermissionAction.CREATE,
    group: PermissionGroup.REASONS,
  },
  {
    id: 29,
    name: 'Update Reasons',
    action: PermissionAction.UPDATE,
    group: PermissionGroup.REASONS,
  },
  {
    id: 30,
    name: 'View Reasons',
    action: PermissionAction.VIEW,
    group: PermissionGroup.REASONS,
  },
  {
    id: 31,
    name: 'Delete Reasons',
    action: PermissionAction.DELETE,
    group: PermissionGroup.REASONS,
  },
  {
    id: 32,
    name: 'Create Documents',
    action: PermissionAction.CREATE,
    group: PermissionGroup.DOCUMENTS,
  },
  {
    id: 33,
    name: 'Update Documents',
    action: PermissionAction.UPDATE,
    group: PermissionGroup.DOCUMENTS,
  },
  {
    id: 34,
    name: 'View Documents',
    action: PermissionAction.VIEW,
    group: PermissionGroup.DOCUMENTS,
  },
  {
    id: 35,
    name: 'Delete Documents',
    action: PermissionAction.DELETE,
    group: PermissionGroup.DOCUMENTS,
  },
  {
    id: 36,
    name: 'Create Locations',
    action: PermissionAction.CREATE,
    group: PermissionGroup.LOCATIONS,
  },
  {
    id: 37,
    name: 'Update Locations',
    action: PermissionAction.UPDATE,
    group: PermissionGroup.LOCATIONS,
  },
  {
    id: 38,
    name: 'View Locations',
    action: PermissionAction.VIEW,
    group: PermissionGroup.LOCATIONS,
  },
  {
    id: 39,
    name: 'Delete Locations',
    action: PermissionAction.DELETE,
    group: PermissionGroup.LOCATIONS,
  },
  {
    id: 40,
    name: 'Update Complains',
    action: PermissionAction.UPDATE,
    group: PermissionGroup.COMPLAINS,
  },
  {
    id: 41,
    name: 'View Complains',
    action: PermissionAction.VIEW,
    group: PermissionGroup.COMPLAINS,
  },
  {
    id: 42,
    name: 'Delete Complains',
    action: PermissionAction.DELETE,
    group: PermissionGroup.COMPLAINS,
  },
  {
    id: 43,
    name: 'View Reviews',
    action: PermissionAction.VIEW,
    group: PermissionGroup.REVIEWS,
  },
  {
    id: 44,
    name: 'Delete Reviews',
    action: PermissionAction.DELETE,
    group: PermissionGroup.REVIEWS,
  },
  {
    id: 45,
    name: 'Create On Boarding Screen',
    action: PermissionAction.CREATE,
    group: PermissionGroup.ON_BOARDING_SCREENS,
  },
  {
    id: 46,
    name: 'Update On Boarding Screen',
    action: PermissionAction.UPDATE,
    group: PermissionGroup.ON_BOARDING_SCREENS,
  },
  {
    id: 47,
    name: 'View On Boarding Screen',
    action: PermissionAction.VIEW,
    group: PermissionGroup.ON_BOARDING_SCREENS,
  },
  {
    id: 48,
    name: 'Delete On Boarding Screen',
    action: PermissionAction.DELETE,
    group: PermissionGroup.ON_BOARDING_SCREENS,
  },
  {
    id: 49,
    name: 'Create Settings',
    action: PermissionAction.CREATE,
    group: PermissionGroup.SETTINGS,
  },
  {
    id: 50,
    name: 'Update Settings',
    action: PermissionAction.UPDATE,
    group: PermissionGroup.SETTINGS,
  },
  {
    id: 51,
    name: 'View Settings',
    action: PermissionAction.VIEW,
    group: PermissionGroup.SETTINGS,
  },
  {
    id: 52,
    name: 'Delete Settings',
    action: PermissionAction.DELETE,
    group: PermissionGroup.SETTINGS,
  },
  {
    id: 53,
    name: 'View Reports',
    action: PermissionAction.VIEW,
    group: PermissionGroup.REPORTS,
  },
  {
    id: 54,
    name: 'Update Attachments',
    action: PermissionAction.UPDATE,
    group: PermissionGroup.ATTACHMENTS,
  },
  {
    id: 55,
    name: 'Delete Attachments',
    action: PermissionAction.DELETE,
    group: PermissionGroup.ATTACHMENTS,
  },
  {
    id: 56,
    name: 'Create Notifications',
    action: PermissionAction.CREATE,
    group: PermissionGroup.NOTIFICATIONS,
  },
  {
    id: 57,
    name: 'Export Backups',
    action: PermissionAction.EXPORT,
    group: PermissionGroup.BACKUPS,
  },
  {
    id: 58,
    name: 'Import Backups',
    action: PermissionAction.IMPORT,
    group: PermissionGroup.BACKUPS,
  },
];
