export abstract class Constants {
  static ADMINS_MICROSERVICE_VERSION = '1';
  static CUSTOMERS_MICROSERVICE_VERSION = '1';
  static LOCATIONS_MICROSERVICE_VERSION = '1';
  static VENDORS_MICROSERVICE_VERSION = '1';
  static DOCUMENTS_MICROSERVICE_VERSION = '1';
}
